export const CustomErrors = {
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_LOGIN_OR_PASSWORD: 'INVALID_LOGIN_OR_PASSWORD',
  UNAUTHORIZED: 'UNAUTHORIZED',

  ACCESS_DENIED: 'ACCESS_DENIED',

  USER_IS_NOT_EXIST: 'USER_IS_NOT_EXIST',

  DELETE_USER_ERROR: 'DELETE_USER_ERROR',

  // validation errors
  PASSWORD_IS_NOT_VALID_FORMAT: 'PASSWORD_IS_NOT_VALID_FORMAT',
  LOGIN_IS_NOT_VALID_FORMAT: 'LOGIN_IS_NOT_VALID_FORMAT',

  // file errors
  FILE_SIZE_LIMIT: 'FILE_SIZE_LIMIT',
  FILE_UPLOAD_ERROR: 'FILE_UPLOAD_ERROR',
  FILE_REMOVE_ERROR: 'FILE_REMOVE_ERROR',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
};
